apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: custom-app
        image: <your-dockerhub-username>/custom-app:1.1
        ports:
        - containerPort: 4000
